/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wysaid_gpuimage_android_CGENativeLibrary */

#ifndef _Included_org_wysaid_gpuimage_android_CGENativeLibrary
#define _Included_org_wysaid_gpuimage_android_CGENativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wysaid_gpuimage_android_CGENativeLibrary
 * Method:    _globalInit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_wysaid_gpuimage_1android_CGENativeLibrary__1globalInit
  (JNIEnv *, jclass);

/*
 * Class:     org_wysaid_gpuimage_android_CGENativeLibrary
 * Method:    _globalRelease
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wysaid_gpuimage_1android_CGENativeLibrary__1globalRelease
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
